import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Aside from "@/components/layout/aside";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="id"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col-reverse md:flex-row md:h-screen md:overflow-hidden">
        <Aside />
        <main className="flex-1 overflow-auto md:overflow-hidden md:h-full bg-white pb-[4.25rem] md:pb-0">{children}</main>
      </body>
    </html>
  );
}
